# pip install if needed

In [ ]:
!pip install folium mapclassify
!pip install ipywidgets
!pip install leafmap
!pip install lonboard palettable sidecar

In [ ]:
!pip install lonboard palettable sidecar

In [ ]:
!pip install geopandas

In [ ]:
!pip install leafmap

# Imports

In [1]:
from pathlib import Path

import geopandas as gpd
import pandas as pd
import zipfile
import requests
from datetime import datetime, timedelta
import os
from tqdm import tqdm
import matplotlib.pyplot as plt
import leafmap
import shapely
from palettable.colorbrewer.diverging import BrBG_10
from sidecar import Sidecar

import folium
from folium import GeoJson
from shapely.geometry import mapping


from lonboard import Map, ScatterplotLayer
from lonboard.colormap import apply_continuous_cmap
from sqlalchemy import create_engine
import duckdb

import random

import pyarrow.parquet as pq

# LOAD USA AND TERRITORIES

In [179]:
usa_states = gpd.read_file("/Users/jaranda02/Desktop/Capstone/cb_2021_us_state_20m/cb_2021_us_state_20m.shp")

# Merge all states into one polygon (includes AK, HI, PR, etc.)
usa_full = usa_states.dissolve(by='NAME')

## LOAD SMOKE SHAPEFILE SCRIPT

In [103]:
base_dir = "/Users/jaranda02/Desktop/Capstone/hms_smoke_2023_to_2024"

smoke = []

for folder in tqdm(sorted(os.listdir(base_dir))):
    folder_path = os.path.join(base_dir, folder)

    if os.path.isdir(folder_path):
        # Extract the date string from folder name (assumes format: hms_smoke_YYYYMMDD)
        try:
            date_str = folder.split("_")[-1]  # "20230101"
            date = pd.to_datetime(date_str, format="%Y%m%d")
        except Exception as e:
            print(f"Skipping folder {folder} due to date parsing error: {e}")
            continue

        # Look for .shp file inside the folder
        for file in os.listdir(folder_path):
            if file.endswith(".shp"):
                shp_path = os.path.join(folder_path, file)
                try:
                    gdf = gpd.read_file(shp_path)
                    gdf["date"] = date  # assign parsed date
                    smoke.append(gdf)
                except Exception as e:
                    print(f"Failed to read {shp_path}: {e}")
                break  # Only one shapefile per folder

# Combine all into one GeoDataFrame
if smoke:
    all_smoke_gdf = gpd.GeoDataFrame(pd.concat(smoke, ignore_index=True))
    all_smoke_gdf.head()
else:
    print("No shapefiles loaded.")

all_smoke_gdf["smoke_id"] = all_smoke_gdf.index

100%|████████████████████████████████████████| 732/732 [00:01<00:00, 515.87it/s]

In [171]:
all_smoke_gdf.to_parquet("all_smoke.parquet",index=True)

## LOAD FIRE SHAPEFILE SCRIPT

In [85]:
# Set the path to your fire shapefiles folder
base_dir = "/Users/jaranda02/Desktop/Capstone/hms_shapefile_fire_2023_to_2024"

# Empty list to store daily GeoDataFrames
fire = []

# Loop through each subfolder (one per day)
for folder in tqdm(sorted(os.listdir(base_dir))):
    folder_path = os.path.join(base_dir, folder)

    if os.path.isdir(folder_path):
        try:
            # Extract date from folder name: e.g., 'hms_fire_20230101' -> '20230101'
            date_str = folder.split("_")[-1]
            date = pd.to_datetime(date_str, format="%Y%m%d")
        except Exception as e:
            print(f"Skipping folder {folder}: couldn't parse date - {e}")
            continue

        # Look for the .shp file inside the folder
        for file in os.listdir(folder_path):
            if file.endswith(".shp"):
                shp_path = os.path.join(folder_path, file)
                try:
                    gdf = gpd.read_file(shp_path)
                    gdf["date"] = date  # Add a date column
                    fire.append(gdf)
                except Exception as e:
                    print(f"Failed to read {shp_path}: {e}")
                break  # Only one shapefile per folder

# Combine all GeoDataFrames into one
if fire:
    all_fire_gdf = gpd.GeoDataFrame(pd.concat(fire, ignore_index=True))
    all_fire_gdf.head()
else:
    print("No fire shapefiles were successfully loaded.")

all_fire_gdf["fire_id"] = all_fire_gdf.index

100%|█████████████████████████████████████████| 732/732 [02:20<00:00,  5.22it/s]

In [173]:
all_fire_gdf.to_parquet("all_fire.parquet",index=True)

# keep only within usa and us territories

In [44]:
def convert_yearday_time(df, yearday_col='YearDay', time_col='Time'):
    # Zero-pad Time values (e.g. 520 → 0520)
    df[time_col] = df[time_col].astype(str).str.zfill(4)

    # Combine YearDay and Time into a single string
    datetime_str = df[yearday_col].astype(str) + df[time_col]

    # Convert to datetime using custom format: %Y%j%H%M
    df['datetime_full'] = pd.to_datetime(datetime_str, format='%Y%j%H%M')

    return df

In [147]:
def convert_smoke_start_end(df, start_col='Start', end_col='End'):
    # Split start column
    start_split = df[start_col].astype(str).str.split(" ", expand=True)
    start_yearday = start_split[0]
    start_time = start_split[1].str.zfill(4)
    start_str = start_yearday + start_time
    df['start_datetime'] = pd.to_datetime(start_str, format='%Y%j%H%M')

    # Split end column
    end_split = df[end_col].astype(str).str.split(" ", expand=True)
    end_yearday = end_split[0]
    end_time = end_split[1].str.zfill(4)
    end_str = end_yearday + end_time
    df['end_datetime'] = pd.to_datetime(end_str, format='%Y%j%H%M')

    return df

In [187]:
# filter to only include fire and smoke that occur within the USA and its territories
fire_in_usa = all_fire_gdf[all_fire_gdf.geometry.within(usa_full.unary_union)]
smoke_in_usa = all_smoke_gdf[all_smoke_gdf.geometry.intersects(usa_full.unary_union)]

NameError: name 'all_smoke_gdf' is not defined

In [ ]:
fire_in_usa

In [ ]:
smoke_in_usa

In [ ]:
fire_in_usa = convert_yearday_time(fire_in_usa)
fire_in_usa

#fire_in_usa.to_file("fire_in_usa.shp")

In [ ]:
smoke_in_usa = convert_smoke_start_end(smoke_in_usa)
smoke_in_usa

#smoke_in_usa.to_file("smoke_in_usa.shp")

# convert to parquet

In [251]:
fire_in_usa.to_parquet("fire_in_usa.parquet", index=True)

In [3]:
smoke_in_usa.to_parquet("smoke_in_usa.parquet", index=True)

NameError: name 'smoke_in_usa' is not defined

In [ ]:
smoke_buffer10km = smoke_in_usa.copy()
smoke_buffer10km["geometry"] = smoke_buffer10km.geometry.buffer(10000)

smoke_buffer10km.to_parquet("smoke_buffer10km.parquet", index=True)

smoke_buffer5km = smoke_in_usa.copy()
smoke_buffer5km["geometry"] = smoke_buffer5km.geometry.buffer(5000)

smoke_buffer5km.to_parquet("smoke_buffer5km.parquet", index=True)

# DUCKDB setup

In [7]:
con = duckdb.connect()
con.query('INSTALL spatial')
con.query('LOAD spatial')

# Loading Tables

In [169]:
fire_in_usa_test = con.execute("""
    SELECT * 
    FROM 'fire_in_usa.parquet'
""").fetchdf()

In [171]:
fire_in_usa_test.head()

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,datetime_full,__index_level_0__,fire_id
0,-81.041359,26.774929,2024044,1510,GOES-EAST,FDC,94,83.026,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-02-13,2024-02-13 15:10:00,8388608,1451209

In [159]:
smoke_in_usa = con.execute("""
    SELECT * 
    FROM 'smoke_in_usa.parquet'
""").fetchdf()

In [ ]:
smoke_in_usa.head()

In [149]:
fire_in_usa["fire_id"] = fire_in_usa.index
fire_in_usa.to_parquet("fire_in_usa.parquet", index=False)
fire_in_usa

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,datetime_full,__index_level_0__,fire_id
0,-77.669014,38.735313,2023001,0638,SUOMI NPP,VIIRS,24,1.386,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,2023-01-01 06:38:00,29,0
1,-83.262901,37.364960,2023001,0638,SUOMI NPP,VIIRS,25,0.422,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,2023-01-01 06:38:00,30,1
2,-79.400337,34.792572,2023001,0641,SUOMI NPP,VIIRS,35,1.153,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,2023-01-01 06:41:00,34,2
3,-79.400948,34.788376,2023001,0641,SUOMI NPP,VIIRS,35,1.153,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,2023-01-01 06:41:00,35,3
4,-84.171059,33.103317,2023001,0641,SUOMI NPP,VIIRS,27,0.894,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,2023-01-01 06:41:00,36,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3749331,-82.238770,32.283287,2025001,0120,GOES-EAST,FDC,31,32.289,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,2025-01-01 01:20:00,16630793,3749331
3749332,-82.238770,32.283287,2025001,0121,GOES-EAST,FDC,31,25.670,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,2025-01-01 01:21:00,16630795,3749332
3749333,-82.238770,32.283287,2025001,0126,GOES-EAST,FDC,31,28.718,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,2025-01-01 01:26:00,16630802,3749333
3749334,-82.238770,32.283287,2025001,0130,GOES-EAST,FDC,31,24.417,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,2025-01-01 01:30:00,16630805,3749334
3749335,-82.238770,32.283287,2025001,0140,GOES-EAST,FDC,31,25.476,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,2025-01-01 01:40:00,16630814,3749335

In [153]:
smoke_in_usa["smoke_id"] = smoke_in_usa.index
smoke_in_usa.to_parquet("smoke_in_usa.parquet", index=False)
smoke_in_usa

,Satellite,Start,End,Density,geometry,date,start_datetime,end_datetime,__index_level_0__,smoke_id
0,GOES-WEST,2023001 1300,2023001 1520,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 95, 45, 200, 194, 235...",2023-01-01,2023-01-01 13:00:00,2023-01-01 15:20:00,5,0
1,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 202, 7, 162, 194, 20,...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,10,1
2,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11,2
3,GOES-EAST,2023002 1520,2023002 1650,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 149, 97, 162, 194, 29...",2023-01-02,2023-01-02 15:20:00,2023-01-02 16:50:00,12,3
4,GOES-EAST,2023002 1640,2023002 1810,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 40, 186, 161, 194, 22...",2023-01-02,2023-01-02 16:40:00,2023-01-02 18:10:00,13,4
...,...,...,...,...,...,...,...,...,...,...
22600,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839,22600
22601,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 153, 118, 183, 194, 1...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32840,22601
22602,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 55, 87, 187, 194, 235...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32841,22602
22603,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 24, 22, 197, 194, 218...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32842,22603
22604,GOES-EAST,2024366 1740,2024366 2210,Medium,"[2, 4, 0, 0, 0, 0, 0, 0, 151, 223, 196, 194, 1...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32846,22604

# Filtering Data using duckdb

In [266]:
df

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,...,__index_level_0__,Satellite_1,Start,End,Density,geometry_1,date_1,start_datetime,end_datetime,__index_level_0___1
0,-91.113426,35.996613,2023172,1500,GOES-EAST,FDC,57,33.974,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349472,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
1,-89.221596,36.805637,2023172,1500,GOES-EAST,FDC,91,294.384,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349473,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
2,-89.215981,36.779930,2023172,1500,GOES-EAST,FDC,57,205.634,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349474,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
3,-89.122818,37.136791,2023172,1500,GOES-EAST,FDC,57,207.088,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349475,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
4,-90.036652,36.726215,2023172,1500,GOES-EAST,FDC,57,36.036,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349487,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2222939,-120.112990,38.232674,2023172,2022,NOAA 20,VIIRS,22,12.282,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4371760,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 249, 155, 240, 194, 1...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11225
2222940,-120.114120,38.236938,2023172,2022,NOAA 20,VIIRS,22,12.282,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4371761,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 249, 155, 240, 194, 1...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11225
2222941,-120.119480,38.235725,2023172,2022,NOAA 20,VIIRS,22,42.973,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4371762,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 249, 155, 240, 194, 1...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11225
2222942,-116.298820,43.471004,2023172,1938,SUOMI NPP,VIIRS,52,52.589,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4366735,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 158, 176, 232, 194, 6...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11228
2222943,-120.344620,37.900054,2023172,1840,GOES-WEST,ANALYSIS,91,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4359775,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 41, 67, 241, 194, 12,...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11226

In [ ]:
df_sorted = df.sort_values(by='datetime_full', ascending=True)
df_sorted

In [131]:
df_unique_fires = df_sorted.drop_duplicates(subset="__index_level_0__")
fire_indices = df_sorted["__index_level_0__"].unique().

In [129]:
len(fire_indices)

1386693

In [ ]:
df_unique_smoke = df_sorted.drop_duplicates(subset="__index_level_0___1")
smoke_indices = df_unique_smoke["__index_level_0___1"]

In [ ]:
df_sorted.to_parquet("fire_smoke_matches.parquet", index=False)

In [ ]:
print(df["__index_level_0__"].unique().shape)

# filtering data with buffer

In [ ]:
buffer_10km_df = con.execute("""
    SELECT f.*, s.* 
    FROM 'fire_in_usa.parquet' f 
    JOIN 'smoke_buffer10km.parquet' s 
    ON ST_Within(f.geometry, s.geometry)
    WHERE f.datetime_full BETWEEN s.start_datetime AND s.end_datetime
""").fetchdf()

In [ ]:
buffer_10km_sorted = buffer_10km_df.sort_values(by='datetime_full', ascending=True)
buffer_10km_sorted

# Cleaning

In [ ]:
fire_df = pd.read_parquet("fire_in_usa.parquet")
print(fire_df.columns)

In [226]:
fire_df["fireid"] = fire_df.index
fire_df

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,datetime_full,fireid
29,-77.669014,38.735313,2023001,0638,SUOMI NPP,VIIRS,24,1.386,b'\x01\x01\x00\x00\x00<\xa4\x18 \xd1jS\xc0m\xa...,2023-01-01,2023-01-01 06:38:00,29
30,-83.262901,37.364960,2023001,0638,SUOMI NPP,VIIRS,25,0.422,b'\x01\x01\x00\x00\x00|E\xb7^\xd3\xd0T\xc0\x91...,2023-01-01,2023-01-01 06:38:00,30
34,-79.400337,34.792572,2023001,0641,SUOMI NPP,VIIRS,35,1.153,b'\x01\x01\x00\x00\x00=\x98\x14\x1f\x9f\xd9S\x...,2023-01-01,2023-01-01 06:41:00,34
35,-79.400948,34.788376,2023001,0641,SUOMI NPP,VIIRS,35,1.153,b'\x01\x01\x00\x00\x00b\xd9\xcc!\xa9\xd9S\xc0\...,2023-01-01,2023-01-01 06:41:00,35
36,-84.171059,33.103317,2023001,0641,SUOMI NPP,VIIRS,27,0.894,b'\x01\x01\x00\x00\x00\xef\xabr\xa1\xf2\nU\xc0...,2023-01-01,2023-01-01 06:41:00,36
...,...,...,...,...,...,...,...,...,...,...,...,...
16630793,-82.238770,32.283287,2025001,0120,GOES-EAST,FDC,31,32.289,b'\x01\x01\x00\x00\x00\x05Q\xf7\x01H\x8fT\xc0\...,2024-12-31,2025-01-01 01:20:00,16630793
16630795,-82.238770,32.283287,2025001,0121,GOES-EAST,FDC,31,25.670,b'\x01\x01\x00\x00\x00\x05Q\xf7\x01H\x8fT\xc0\...,2024-12-31,2025-01-01 01:21:00,16630795
16630802,-82.238770,32.283287,2025001,0126,GOES-EAST,FDC,31,28.718,b'\x01\x01\x00\x00\x00\x05Q\xf7\x01H\x8fT\xc0\...,2024-12-31,2025-01-01 01:26:00,16630802
16630805,-82.238770,32.283287,2025001,0130,GOES-EAST,FDC,31,24.417,b'\x01\x01\x00\x00\x00\x05Q\xf7\x01H\x8fT\xc0\...,2024-12-31,2025-01-01 01:30:00,16630805
16630814,-82.238770,32.283287,2025001,0140,GOES-EAST,FDC,31,25.476,b'\x01\x01\x00\x00\x00\x05Q\xf7\x01H\x8fT\xc0\...,2024-12-31,2025-01-01 01:40:00,16630814

In [ ]:
fire_in_usa

In [ ]:
filtered_fire_df

In [135]:
con.register("index_table", pd.DataFrame({"id": fire_indices}))

In [121]:
len(fire_indices)

1386693

In [133]:
con.execute("""
    CREATE TABLE fire_with_index AS
    SELECT row_number() OVER () AS idx, *
    FROM read_parquet('fire_in_usa.parquet')
""")

CatalogException: Catalog Error: Table with name "fire_with_index" already exists!

In [137]:
clean_fire = con.execute("""
    SELECT f.*
    FROM fire_with_index f
    JOIN index_table i
    ON f.idx = i.id
""").fetchdf()

In [141]:
clean_fire.sort_values(by='datetime_full', ascending=True)

,idx,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,datetime_full,__index_level_0__
146989,1172,-106.448807,45.818657,2023002,2146,GOES-EAST,FDC,40,232.068,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,2023-01-02 21:46:00,4339
146990,1180,-99.388817,33.555729,2023002,2156,GOES-EAST,FDC,41,38.938,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,2023-01-02 21:56:00,4389
146991,1182,-99.388817,33.555725,2023002,2200,GOES-EAST,FDC,41,36.634,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,2023-01-02 22:00:00,4400
146992,1186,-99.388817,33.555729,2023002,2206,GOES-EAST,FDC,41,45.794,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,2023-01-02 22:06:00,4430
146993,1187,-80.462502,26.446548,2023002,2206,GOES-EAST,FDC,27,27.931,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,2023-01-02 22:06:00,4436
...,...,...,...,...,...,...,...,...,...,...,...,...,...
154228,3744584,-91.006500,29.896314,2024359,1819,NOAA 21,ANALYSIS,35,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-24,2024-12-24 18:19:00,16614798
154229,3744687,-89.090927,31.297781,2024359,1819,NOAA 21,VIIRS,27,4.524,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-24,2024-12-24 18:19:00,16614901
154230,3744784,-91.424713,30.397364,2024359,1830,GOES-EAST,FDC,31,120.024,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-24,2024-12-24 18:30:00,16615014
154232,3744974,-83.831810,32.390499,2024359,1843,SUOMI NPP,VIIRS,27,2.013,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-24,2024-12-24 18:43:00,16615252
154231,3744883,-90.997910,29.892849,2024359,1843,SUOMI NPP,VIIRS,35,6.163,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-24,2024-12-24 18:43:00,16615161

In [143]:
filtered_ids = clean_fire["idx"].unique()
all_ids_set = set(fire_indices)
filtered_ids_set = set(filtered_ids)

# What's missing?
missing_ids = all_ids_set - filtered_ids_set

print(f"{len(missing_ids)} IDs are missing")
print(list(missing_ids)[:10])  # preview a few

1228650 IDs are missing
[8388608, 8388609, 8388611, 8388616, 8388617, 8388618, 8388619, 8388625, 16172193, 8388663]

In [165]:
fire_indices_set = set(fire_indices)
clean_fire = all_fire_gdf.loc[all_fire_gdf.index.isin(fire_indices_set)]

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,datetime_full,__index_level_0__,fire_id
1172,-99.388817,33.555729,2023002,2146,GOES-EAST,FDC,41,43.092,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,2023-01-02 21:46:00,4340,1172
1180,-106.448799,45.818661,2023002,2200,GOES-EAST,FDC,40,208.034,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,2023-01-02 22:00:00,4399,1180
1182,-106.448807,45.818657,2023002,2201,GOES-EAST,FDC,40,253.125,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,2023-01-02 22:01:00,4413,1182
1186,-80.462502,26.446548,2023002,2206,GOES-EAST,FDC,27,27.931,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,2023-01-02 22:06:00,4436,1186
1187,-106.448799,45.818661,2023002,2210,GOES-EAST,FDC,40,196.327,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,2023-01-02 22:10:00,4442,1187
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3744584,-91.013053,29.896314,2024359,1819,NOAA 21,ANALYSIS,35,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-24,2024-12-24 18:19:00,16614799,3744584
3744687,-88.273300,31.520664,2024359,1819,NOAA 21,VIIRS,27,5.147,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-24,2024-12-24 18:19:00,16614902,3744687
3744784,-91.104630,30.046743,2024359,1830,GOES-EAST,FDC,31,44.889,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-24,2024-12-24 18:30:00,16615015,3744784
3744883,-91.002190,29.891972,2024359,1843,SUOMI NPP,VIIRS,35,2.856,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-24,2024-12-24 18:43:00,16615162,3744883
3744974,-82.458496,32.624355,2024359,1843,SUOMI NPP,VIIRS,31,5.443,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-24,2024-12-24 18:43:00,16615253,3744974

# Exploration

In [ ]:
all_fire_gdf.shape

In [ ]:
all_smoke_gdf

In [ ]:
all_smoke_gdf['date'] = pd.to_datetime(all_smoke_gdf['date'])
smoke_on_jan1 = all_smoke_gdf[all_smoke_gdf['date'] == pd.Timestamp('2024-01-01')]
smoke_on_jan1["area"] = smoke_on_jan1.geometry.area
smoke_on_jan1

In [ ]:
all_fire_gdf['date'] = pd.to_datetime(all_fire_gdf['date'])
fire_on_jan1 = all_fire_gdf[all_fire_gdf['date'] == pd.Timestamp('2024-01-01')]
fire_on_jan1

In [ ]:
smoke_on_jan1.explore()

In [ ]:
smoke_on_jan1.shape

# SANITY CHECK

In [ ]:
# setting a random date

def randomDates():
    start_date = datetime(2023, 1, 1)
    end_date = datetime(2024, 12, 31)

    # Calculate the number of days between the two dates
    delta = end_date - start_date

    # Generate a random number of days to add
    random_days = random.randint(0, delta.days)

    # Create the random date
    random_date = start_date + timedelta(days=random_days)

    # Format the date as YYYY-MM-DD
    return random_date.strftime('%Y-%m-%d')


num = 3 
random_dates = sorted([randomDates() for _ in range(num)])

print(random_dates)

In [ ]:
n = 0

In [ ]:
all_smoke_gdf['date'] = pd.to_datetime(all_smoke_gdf['date'])
smoke_on_date = all_smoke_gdf[all_smoke_gdf['date'] == pd.Timestamp(random_dates[n]) ]
smoke_on_date["area"] = smoke_on_date.geometry.area
smoke_on_date.shape

In [ ]:
# returns fires from random date [n]
fire_on_date = all_fire_gdf[all_fire_gdf['date'] == pd.Timestamp(random_dates[n]) ]
fire_on_date.shape

In [ ]:
def show_fire_smoke_map(fire_on_date, smoke_on_date):

  m = folium.Map()
    # Fallback center if fire data is empty
  if not smoke_on_date.empty:
    smoke_copy = smoke_on_date.copy()

    # Convert datetimes to strings
    for col in smoke_copy.select_dtypes(include=['datetime64[ns]', 'datetime64']):
        smoke_copy[col] = smoke_copy[col].astype(str)

    # Define a default get_color function
    def get_color(density):
        return 'gray'  # fallback color if density info is missing

    if 'density' in smoke_copy.columns:
        # Normalize the density values
        max_density = smoke_copy['density'].max()
        min_density = smoke_copy['density'].min()
        range_density = max_density - min_density if max_density != min_density else 1

        def get_color(density):  # overwrite fallback
            norm = (density - min_density) / range_density
            if norm < 0.33:
                return 'yellow'    # Low density
            elif norm < 0.66:
                return 'orange'    # Medium density
            else:
                return 'red'       # High density

    def style_function(feature):
        density = feature['properties'].get('density', 0)
        return {
            'fillColor': get_color(density),
            'color': get_color(density),
            'weight': 1,
            'fillOpacity': 0.5
        }

    folium.GeoJson(
        smoke_copy.to_json(),
        name='Smoke Layer',
        style_function=style_function,
        tooltip=folium.GeoJsonTooltip(fields=['density'] if 'density' in smoke_copy.columns else [])
    ).add_to(m)

    return m

In [ ]:
show_fire_smoke_map(fire_on_date, smoke_on_date)

In [ ]:
def filter_fire_near_smoke(fire, smoke, buffer_km=10):
    smoke_buffered = smoke.copy()
    smoke_buffered['geometry'] = smoke_buffered.geometry.buffer(buffer_km * 1000)

    # Spatial join: find fires within (buffered) smoke polygons
    fire_near_smoke = gpd.sjoin(fire, smoke_buffered, how='inner', predicate='intersects')
    fire_near_smoke = fire_near_smoke.drop_duplicates(subset='geometry')

    return fire_near_smoke

In [ ]:
def filter_smoke_with_fire(smoke, fire, buffer_km=10):

    smoke_buffered = smoke.copy()
    smoke_buffered["geometry"] = smoke_buffered.geometry.buffer(buffer_km * 1000)

    # Spatial join: which fire points intersect the buffered smoke polygons
    joined = gpd.sjoin(smoke_buffered, fire, how='inner', predicate='intersects')

    # Keep only original smoke polygons whose buffered versions had fire points
    smoke_with_fire = smoke.loc[smoke.index.isin(joined.index)]
    smoke_with_fire = smoke_with_fire.drop_duplicates(subset='geometry')

    return smoke_with_fire

In [ ]:
filter_smoke = filter_smoke_with_fire(smoke_on_date, fire_on_date)
filter_smoke.shape

In [ ]:
filter_fire = filter_fire_near_smoke(fire_on_date,smoke_on_date)
filter_fire.shape

In [ ]:
fire = all_fire_gdf.to_crs(usa_full.crs)
smoke = all_smoke_gdf.to_crs(usa_full.crs)

# help me

In [212]:
fire_in_usa_pd = con.execute("""
    SELECT * 
    FROM 'fire_in_usa.parquet'
""").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [214]:
fire_in_usa_pd

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,datetime_full,__index_level_0__,fire_id
0,-77.669014,38.735313,2023001,0638,SUOMI NPP,VIIRS,24,1.386,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,2023-01-01 06:38:00,29,0
1,-83.262901,37.364960,2023001,0638,SUOMI NPP,VIIRS,25,0.422,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,2023-01-01 06:38:00,30,1
2,-79.400337,34.792572,2023001,0641,SUOMI NPP,VIIRS,35,1.153,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,2023-01-01 06:41:00,34,2
3,-79.400948,34.788376,2023001,0641,SUOMI NPP,VIIRS,35,1.153,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,2023-01-01 06:41:00,35,3
4,-84.171059,33.103317,2023001,0641,SUOMI NPP,VIIRS,27,0.894,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,2023-01-01 06:41:00,36,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3749331,-82.238770,32.283287,2025001,0120,GOES-EAST,FDC,31,32.289,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,2025-01-01 01:20:00,16630793,3749331
3749332,-82.238770,32.283287,2025001,0121,GOES-EAST,FDC,31,25.670,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,2025-01-01 01:21:00,16630795,3749332
3749333,-82.238770,32.283287,2025001,0126,GOES-EAST,FDC,31,28.718,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,2025-01-01 01:26:00,16630802,3749333
3749334,-82.238770,32.283287,2025001,0130,GOES-EAST,FDC,31,24.417,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,2025-01-01 01:30:00,16630805,3749334
3749335,-82.238770,32.283287,2025001,0140,GOES-EAST,FDC,31,25.476,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,2025-01-01 01:40:00,16630814,3749335

In [139]:
fire_df = pd.read_parquet('fire_in_usa.parquet')
iltered_fire_df = fire_df.loc[fire_df.index.isin(fire_indices)]
iltered_fire_df
iltered_fire_df = convert_yearday_time(iltered_fire_df)

In [ ]:
filtered_fire_nogeo = iltered_fire_df.drop(columns=["geometry"])
filtered_fire_nogeo

In [155]:
filtered_fire_nogeo.to_parquet("filtered_fire_nogeo.parquet", index=True)

In [151]:
smoke_df = pd.read_parquet('smoke_in_usa.parquet')
filtered_smoke_df = smoke_df.loc[smoke_df.index.isin(smoke_indices)]
filtered_smoke_df  = convert_smoke_start_end(filtered_smoke_df)
filtered_smoke_df

,Satellite,Start,End,Density,geometry,date,start_datetime,end_datetime,__index_level_0__,smoke_id
10,GOES-EAST,2023002 2100,2023002 2230,Light,b'\x02\x04\x00\x00\x00\x00\x00\x00\x9dh\xc5\xc...,2023-01-02,2023-01-02 21:00:00,2023-01-02 22:30:00,29,10
11,GOES-EAST,2023002 2100,2023002 2230,Light,b'\x02\x04\x00\x00\x00\x00\x00\x00\x0e\xac\xe5...,2023-01-02,2023-01-02 21:00:00,2023-01-02 22:30:00,30,11
12,GOES-EAST,2023002 2100,2023002 2230,Light,b'\x02\x04\x00\x00\x00\x00\x00\x00e\xbd\xc5\xc...,2023-01-02,2023-01-02 21:00:00,2023-01-02 22:30:00,31,12
13,GOES-EAST,2023003 1230,2023003 1630,Light,b'\x02\x04\x00\x00\x00\x00\x00\x00\xce\xb9\xa1...,2023-01-03,2023-01-03 12:30:00,2023-01-03 16:30:00,33,13
21,GOES-WEST,2023004 1300,2023004 1600,Light,"b""\x02\x04\x00\x00\x00\x00\x00\x00\xc0R\xa2\xc...",2023-01-04,2023-01-04 13:00:00,2023-01-04 16:00:00,44,21
...,...,...,...,...,...,...,...,...,...,...
22597,GOES-EAST,2024365 1900,2024365 2300,Light,b'\x02\x04\x00\x00\x00\x00\x00\x00\x1a\x0c\xb7...,2024-12-30,2024-12-30 19:00:00,2024-12-30 23:00:00,32834,22597
22601,GOES-EAST,2024366 1740,2024366 2210,Light,b'\x02\x04\x00\x00\x00\x00\x00\x00\x99v\xb7\xc...,2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32840,22601
22602,GOES-EAST,2024366 1740,2024366 2210,Light,"b""\x02\x04\x00\x00\x00\x00\x00\x007W\xbb\xc2\x...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32841,22602
22603,GOES-EAST,2024366 1740,2024366 2210,Light,"b""\x02\x04\x00\x00\x00\x00\x00\x00\x18\x16\xc5...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32842,22603
22604,GOES-EAST,2024366 1740,2024366 2210,Medium,b'\x02\x04\x00\x00\x00\x00\x00\x00\x97\xdf\xc4...,2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32846,22604

In [157]:
filtered_smoke_nogeo = filtered_smoke_df.drop(columns=["geometry"])
filtered_smoke_nogeo

,Satellite,Start,End,Density,date,start_datetime,end_datetime,__index_level_0__,smoke_id
10,GOES-EAST,2023002 2100,2023002 2230,Light,2023-01-02,2023-01-02 21:00:00,2023-01-02 22:30:00,29,10
11,GOES-EAST,2023002 2100,2023002 2230,Light,2023-01-02,2023-01-02 21:00:00,2023-01-02 22:30:00,30,11
12,GOES-EAST,2023002 2100,2023002 2230,Light,2023-01-02,2023-01-02 21:00:00,2023-01-02 22:30:00,31,12
13,GOES-EAST,2023003 1230,2023003 1630,Light,2023-01-03,2023-01-03 12:30:00,2023-01-03 16:30:00,33,13
21,GOES-WEST,2023004 1300,2023004 1600,Light,2023-01-04,2023-01-04 13:00:00,2023-01-04 16:00:00,44,21
...,...,...,...,...,...,...,...,...,...
22597,GOES-EAST,2024365 1900,2024365 2300,Light,2024-12-30,2024-12-30 19:00:00,2024-12-30 23:00:00,32834,22597
22601,GOES-EAST,2024366 1740,2024366 2210,Light,2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32840,22601
22602,GOES-EAST,2024366 1740,2024366 2210,Light,2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32841,22602
22603,GOES-EAST,2024366 1740,2024366 2210,Light,2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32842,22603
22604,GOES-EAST,2024366 1740,2024366 2210,Medium,2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32846,22604

In [ ]:
filtered_smoke_nogeo.to_parquet("filtered_smoke_nogeo.parquet", index=True)

# try again

In [11]:
smoke_in_usa = con.execute("""
    SELECT * 
    FROM 'smoke_in_usa.parquet'
""").fetchdf()

In [48]:
smoke_in_usa

,Satellite,Start,End,Density,geometry,date,start_datetime,end_datetime,__index_level_0__,smoke_id
0,GOES-WEST,2023001 1300,2023001 1520,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 95, 45, 200, 194, 235...",2023-01-01,2023-01-01 13:00:00,2023-01-01 15:20:00,5,0
1,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 202, 7, 162, 194, 20,...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,10,1
2,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11,2
3,GOES-EAST,2023002 1520,2023002 1650,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 149, 97, 162, 194, 29...",2023-01-02,2023-01-02 15:20:00,2023-01-02 16:50:00,12,3
4,GOES-EAST,2023002 1640,2023002 1810,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 40, 186, 161, 194, 22...",2023-01-02,2023-01-02 16:40:00,2023-01-02 18:10:00,13,4
...,...,...,...,...,...,...,...,...,...,...
22600,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839,22600
22601,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 153, 118, 183, 194, 1...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32840,22601
22602,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 55, 87, 187, 194, 235...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32841,22602
22603,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 24, 22, 197, 194, 218...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32842,22603
22604,GOES-EAST,2024366 1740,2024366 2210,Medium,"[2, 4, 0, 0, 0, 0, 0, 0, 151, 223, 196, 194, 1...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32846,22604

In [95]:
og_smoke_idx = smoke_in_usa['__index_level_0__']

In [13]:
fire_smoke = con.execute("""
    SELECT * 
    FROM 'fire_smoke_matches.parquet'
""").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [14]:
fire_in_usa = con.execute("""
    SELECT * 
    FROM 'fire_in_usa.parquet'
""").fetchdf()

In [50]:
fire_in_usa["fireid"] = fire_in_usa.index
fire_in_usa

fire_usa_w_og_idx = fire_in_usa = con.execute("""
    SELECT * 
    FROM 'fire_in_usa.parquet'
""").fetchdf()

In [115]:
og_fire_idx = fire_usa_w_og_idx['__index_level_0__']

In [17]:
fire_smoke

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,...,__index_level_0__,Satellite_1,Start,End,Density,geometry_1,date_1,start_datetime,end_datetime,__index_level_0___1
0,-97.835846,26.483723,2023001,1916,GOES-EAST,FDC,41,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1172,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
1,-97.835846,26.483715,2023001,1920,GOES-EAST,FDC,41,299.172,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1182,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
2,-97.812363,26.482916,2023001,1920,GOES-EAST,FDC,94,74.438,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1180,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
3,-97.830475,26.461916,2023001,1921,GOES-EAST,FDC,41,123.735,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1186,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
4,-97.812370,26.482920,2023001,1921,GOES-EAST,FDC,94,149.179,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1189,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2222939,-91.287971,29.711023,2024366,2140,GOES-EAST,FDC,30,25.656,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16630508,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839
2222940,-91.287971,29.711025,2024366,2146,GOES-EAST,FDC,30,24.624,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16630522,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839
2222941,-91.717228,29.921240,2024366,2150,GOES-EAST,ANALYSIS,31,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16630525,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839
2222942,-91.300201,29.721111,2024366,2150,GOES-EAST,ANALYSIS,31,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16630526,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839
2222943,-91.295729,29.721111,2024366,2150,GOES-EAST,ANALYSIS,31,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16630527,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839

In [125]:
fire_indices = fire_smoke["__index_level_0__"].unique()
len(fire_indices)

1386693

In [117]:
smoke_indices = fire_smoke["__index_level_0___1"].unique()
len(smoke_indices)

14081

In [62]:
filtered_smoke = smoke_in_usa.loc[smoke_in_usa['smoke_id'].isin(smoke_indices)]
filtered_smoke

,Satellite,Start,End,Density,geometry,date,start_datetime,end_datetime,__index_level_0__,smoke_id
10,GOES-EAST,2023002 2100,2023002 2230,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 157, 104, 197, 194, 8...",2023-01-02,2023-01-02 21:00:00,2023-01-02 22:30:00,29,10
11,GOES-EAST,2023002 2100,2023002 2230,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 14, 172, 229, 194, 13...",2023-01-02,2023-01-02 21:00:00,2023-01-02 22:30:00,30,11
12,GOES-EAST,2023002 2100,2023002 2230,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 101, 189, 197, 194, 1...",2023-01-02,2023-01-02 21:00:00,2023-01-02 22:30:00,31,12
13,GOES-EAST,2023003 1230,2023003 1630,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 206, 185, 161, 194, 1...",2023-01-03,2023-01-03 12:30:00,2023-01-03 16:30:00,33,13
21,GOES-WEST,2023004 1300,2023004 1600,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 192, 82, 162, 194, 63...",2023-01-04,2023-01-04 13:00:00,2023-01-04 16:00:00,44,21
...,...,...,...,...,...,...,...,...,...,...
22597,GOES-EAST,2024365 1900,2024365 2300,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 26, 12, 183, 194, 87,...",2024-12-30,2024-12-30 19:00:00,2024-12-30 23:00:00,32834,22597
22601,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 153, 118, 183, 194, 1...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32840,22601
22602,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 55, 87, 187, 194, 235...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32841,22602
22603,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 24, 22, 197, 194, 218...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32842,22603
22604,GOES-EAST,2024366 1740,2024366 2210,Medium,"[2, 4, 0, 0, 0, 0, 0, 0, 151, 223, 196, 194, 1...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32846,22604

In [167]:
smoke_ids_df = pd.DataFrame({"smoke_id": og_smoke_idx})
smoke_ids_df.to_csv("filtered_smoke_ids.csv", index=True)

In [169]:
fire_ids_df = pd.DataFrame({"fire_id": og_fire_idx})
fire_ids_df.to_csv("filtered_fire_ids.csv", index=True)

In [105]:
filtered_smoke_gdf = all_smoke_gdf.merge(smoke_ids_df, on="smoke_id", how="inner")
filtered_smoke_gdf

,Satellite,Start,End,Density,geometry,date,smoke_id
0,GOES-WEST,2023001 1300,2023001 1520,Light,"POLYGON ((-96.88264 19.81573, -97.74666 20.020...",2023-01-01,5
1,GOES-EAST,2023001 1900,2023001 2240,Light,"POLYGON ((-81.01521 26.74125, -81.00788 26.665...",2023-01-01,10
2,GOES-EAST,2023001 1900,2023001 2240,Light,"POLYGON ((-91.8009 27.04115, -91.60195 28.1780...",2023-01-01,11
3,GOES-EAST,2023002 1520,2023002 1650,Light,"POLYGON ((-80.58939 26.93243, -80.71756 27.002...",2023-01-02,12
4,GOES-EAST,2023002 1640,2023002 1810,Light,"POLYGON ((-80.61944 27.04644, -80.66217 27.046...",2023-01-02,13
...,...,...,...,...,...,...,...
22600,GOES-EAST,2024366 1740,2024366 2210,Light,"POLYGON ((-92.26113 30.11644, -92.23711 29.963...",2024-12-31,32839
22601,GOES-EAST,2024366 1740,2024366 2210,Light,"POLYGON ((-91.60194 30.83876, -91.67685 30.854...",2024-12-31,32840
22602,GOES-EAST,2024366 1740,2024366 2210,Light,"POLYGON ((-93.64015 30.00864, -93.65804 29.991...",2024-12-31,32841
22603,GOES-EAST,2024366 1740,2024366 2210,Light,"POLYGON ((-98.37118 34.80186, -98.43123 34.744...",2024-12-31,32842
22604,GOES-EAST,2024366 1740,2024366 2210,Medium,"POLYGON ((-98.36845 34.72816, -98.41213 34.646...",2024-12-31,32846

In [121]:
filtered_fire_gdf = all_fire_gdf.merge(fire_ids_df, on="fire_id", how="inner")
filtered_fire_gdf

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,fire_id
0,-77.669014,38.735313,2023001,0638,SUOMI NPP,VIIRS,24,1.386,POINT (-77.66901 38.73531),2023-01-01,29
1,-83.262901,37.364960,2023001,0638,SUOMI NPP,VIIRS,25,0.422,POINT (-83.2629 37.36496),2023-01-01,30
2,-79.400337,34.792572,2023001,0641,SUOMI NPP,VIIRS,35,1.153,POINT (-79.40034 34.79257),2023-01-01,34
3,-79.400948,34.788376,2023001,0641,SUOMI NPP,VIIRS,35,1.153,POINT (-79.40095 34.78838),2023-01-01,35
4,-84.171059,33.103317,2023001,0641,SUOMI NPP,VIIRS,27,0.894,POINT (-84.17106 33.10332),2023-01-01,36
...,...,...,...,...,...,...,...,...,...,...,...
3749331,-82.238770,32.283287,2025001,0120,GOES-EAST,FDC,31,32.289,POINT (-82.23877 32.28329),2024-12-31,16630793
3749332,-82.238770,32.283287,2025001,0121,GOES-EAST,FDC,31,25.670,POINT (-82.23877 32.28329),2024-12-31,16630795
3749333,-82.238770,32.283287,2025001,0126,GOES-EAST,FDC,31,28.718,POINT (-82.23877 32.28329),2024-12-31,16630802
3749334,-82.238770,32.283287,2025001,0130,GOES-EAST,FDC,31,24.417,POINT (-82.23877 32.28329),2024-12-31,16630805
3749335,-82.238770,32.283287,2025001,0140,GOES-EAST,FDC,31,25.476,POINT (-82.23877 32.28329),2024-12-31,16630814

In [123]:
filtered_fire_gdf = convert_yearday_time(filtered_fire_gdf)