# pip install if needed

In [ ]:
!pip install folium mapclassify
!pip install ipywidgets
!pip install leafmap
!pip install lonboard palettable sidecar

In [ ]:
!pip install lonboard palettable sidecar

In [ ]:
!pip install geopandas

In [ ]:
!pip install leafmap

# Imports

In [1]:
from pathlib import Path

import geopandas as gpd
import pandas as pd
import zipfile
import requests
from datetime import datetime, timedelta
import os
from tqdm import tqdm
import matplotlib.pyplot as plt
import leafmap
import shapely
from palettable.colorbrewer.diverging import BrBG_10
from sidecar import Sidecar

import folium
from folium import GeoJson
from shapely.geometry import mapping


from lonboard import Map, ScatterplotLayer
from lonboard.colormap import apply_continuous_cmap
from sqlalchemy import create_engine
import duckdb

import random

import pyarrow.parquet as pq

# LOAD USA AND TERRITORIES

In [3]:
usa_states = gpd.read_file("/Users/jaranda02/Desktop/Capstone/cb_2021_us_state_20m/cb_2021_us_state_20m.shp")

# Merge all states into one polygon (includes AK, HI, PR, etc.)
usa_full = usa_states.dissolve(by='NAME')

## LOAD SMOKE SHAPEFILE SCRIPT

In [5]:
base_dir = "/Users/jaranda02/Desktop/Capstone/hms_smoke_2023_to_2024"

smoke = []

for folder in tqdm(sorted(os.listdir(base_dir))):
    folder_path = os.path.join(base_dir, folder)

    if os.path.isdir(folder_path):
        # Extract the date string from folder name (assumes format: hms_smoke_YYYYMMDD)
        try:
            date_str = folder.split("_")[-1]  # "20230101"
            date = pd.to_datetime(date_str, format="%Y%m%d")
        except Exception as e:
            print(f"Skipping folder {folder} due to date parsing error: {e}")
            continue

        # Look for .shp file inside the folder
        for file in os.listdir(folder_path):
            if file.endswith(".shp"):
                shp_path = os.path.join(folder_path, file)
                try:
                    gdf = gpd.read_file(shp_path)
                    gdf["date"] = date  # assign parsed date
                    smoke.append(gdf)
                except Exception as e:
                    print(f"Failed to read {shp_path}: {e}")
                break  # Only one shapefile per folder

# Combine all into one GeoDataFrame
if smoke:
    all_smoke_gdf = gpd.GeoDataFrame(pd.concat(smoke, ignore_index=True))
    all_smoke_gdf.head()
else:
    print("No shapefiles loaded.")

100%|████████████████████████████████████████| 732/732 [00:02<00:00, 306.28it/s]

## LOAD FIRE SHAPEFILE SCRIPT

In [6]:
# Set the path to your fire shapefiles folder
base_dir = "/Users/jaranda02/Desktop/Capstone/hms_shapefile_fire_2023_to_2024"

# Empty list to store daily GeoDataFrames
fire = []

# Loop through each subfolder (one per day)
for folder in tqdm(sorted(os.listdir(base_dir))):
    folder_path = os.path.join(base_dir, folder)

    if os.path.isdir(folder_path):
        try:
            # Extract date from folder name: e.g., 'hms_fire_20230101' -> '20230101'
            date_str = folder.split("_")[-1]
            date = pd.to_datetime(date_str, format="%Y%m%d")
        except Exception as e:
            print(f"Skipping folder {folder}: couldn't parse date - {e}")
            continue

        # Look for the .shp file inside the folder
        for file in os.listdir(folder_path):
            if file.endswith(".shp"):
                shp_path = os.path.join(folder_path, file)
                try:
                    gdf = gpd.read_file(shp_path)
                    gdf["date"] = date  # Add a date column
                    fire.append(gdf)
                except Exception as e:
                    print(f"Failed to read {shp_path}: {e}")
                break  # Only one shapefile per folder

# Combine all GeoDataFrames into one
if fire:
    all_fire_gdf = gpd.GeoDataFrame(pd.concat(fire, ignore_index=True))
    all_fire_gdf.head()
else:
    print("No fire shapefiles were successfully loaded.")

100%|█████████████████████████████████████████| 732/732 [02:25<00:00,  5.03it/s]

# keep only within usa and us territories

In [9]:
def convert_yearday_time(df, yearday_col='YearDay', time_col='Time'):
    # Zero-pad Time values (e.g. 520 → 0520)
    df[time_col] = df[time_col].astype(str).str.zfill(4)

    # Combine YearDay and Time into a single string
    datetime_str = df[yearday_col].astype(str) + df[time_col]

    # Convert to datetime using custom format: %Y%j%H%M
    df['datetime_full'] = pd.to_datetime(datetime_str, format='%Y%j%H%M')

    return df

In [11]:
def convert_smoke_start_end(df, start_col='Start', end_col='End'):
    # Split start column
    start_split = df[start_col].astype(str).str.split(" ", expand=True)
    start_yearday = start_split[0]
    start_time = start_split[1].str.zfill(4)
    start_str = start_yearday + start_time
    df['start_datetime'] = pd.to_datetime(start_str, format='%Y%j%H%M')

    # Split end column
    end_split = df[end_col].astype(str).str.split(" ", expand=True)
    end_yearday = end_split[0]
    end_time = end_split[1].str.zfill(4)
    end_str = end_yearday + end_time
    df['end_datetime'] = pd.to_datetime(end_str, format='%Y%j%H%M')

    return df

In [ ]:
# filter to only include fire and smoke that occur within the USA and its territories
fire_in_usa = all_fire_gdf[all_fire_gdf.geometry.within(usa_full.unary_union)]
smoke_in_usa = all_smoke_gdf[all_smoke_gdf.geometry.intersects(usa_full.unary_union)]

In [ ]:
fire_in_usa

In [ ]:
smoke_in_usa

In [ ]:
fire_in_usa = convert_yearday_time(fire_in_usa)
fire_in_usa

#fire_in_usa.to_file("fire_in_usa.shp")

In [ ]:
smoke_in_usa = convert_smoke_start_end(smoke_in_usa)
smoke_in_usa

#smoke_in_usa.to_file("smoke_in_usa.shp")

# convert to parquet

In [96]:
#fire_in_usa.to_parquet("fire_in_usa.parquet", index=True)

In [97]:
#smoke_in_usa.to_parquet("smoke_in_usa.parquet", index=True)

In [ ]:
smoke_buffer10km = smoke_in_usa.copy()
smoke_buffer10km["geometry"] = smoke_buffer10km.geometry.buffer(10000)

smoke_buffer10km.to_parquet("smoke_buffer10km.parquet", index=True)

smoke_buffer5km = smoke_in_usa.copy()
smoke_buffer5km["geometry"] = smoke_buffer5km.geometry.buffer(5000)

smoke_buffer5km.to_parquet("smoke_buffer5km.parquet", index=True)

# Filtering Data using duckdb

In [5]:
con = duckdb.connect()
con.query('INSTALL spatial')
con.query('LOAD spatial')

In [7]:
df = con.execute("""
    SELECT f.*, s.*
    FROM 'fire_in_usa.parquet' f
    JOIN 'smoke_in_usa.parquet' s
    ON ST_Within(f.geometry, s.geometry)
    WHERE f.datetime_full BETWEEN s.start_datetime AND s.end_datetime
""").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [9]:
df

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,...,__index_level_0__,Satellite_1,Start,End,Density,geometry_1,date_1,start_datetime,end_datetime,__index_level_0___1
0,-91.113426,35.996613,2023172,1500,GOES-EAST,FDC,57,33.974,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349472,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
1,-89.221596,36.805637,2023172,1500,GOES-EAST,FDC,91,294.384,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349473,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
2,-89.215981,36.779930,2023172,1500,GOES-EAST,FDC,57,205.634,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349474,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
3,-89.122818,37.136791,2023172,1500,GOES-EAST,FDC,57,207.088,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349475,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
4,-90.036652,36.726215,2023172,1500,GOES-EAST,FDC,57,36.036,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349487,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2222939,-120.112990,38.232674,2023172,2022,NOAA 20,VIIRS,22,12.282,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4371760,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 249, 155, 240, 194, 1...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11225
2222940,-120.114120,38.236938,2023172,2022,NOAA 20,VIIRS,22,12.282,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4371761,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 249, 155, 240, 194, 1...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11225
2222941,-120.119480,38.235725,2023172,2022,NOAA 20,VIIRS,22,42.973,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4371762,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 249, 155, 240, 194, 1...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11225
2222942,-116.298820,43.471004,2023172,1938,SUOMI NPP,VIIRS,52,52.589,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4366735,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 158, 176, 232, 194, 6...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11228
2222943,-120.344620,37.900054,2023172,1840,GOES-WEST,ANALYSIS,91,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4359775,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 41, 67, 241, 194, 12,...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11226

In [13]:
df_sorted = df.sort_values(by='datetime_full', ascending=True)
df_sorted

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,...,__index_level_0__,Satellite_1,Start,End,Density,geometry_1,date_1,start_datetime,end_datetime,__index_level_0___1
1305111,-97.835846,26.483723,2023001,1916,GOES-EAST,FDC,41,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1172,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
1305110,-97.835846,26.483715,2023001,1920,GOES-EAST,FDC,41,299.172,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1182,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
1305109,-97.812363,26.482916,2023001,1920,GOES-EAST,FDC,94,74.438,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1180,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
1305105,-97.830475,26.461916,2023001,1921,GOES-EAST,FDC,41,123.735,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1186,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
1305108,-97.812370,26.482920,2023001,1921,GOES-EAST,FDC,94,149.179,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1189,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6227,-91.287971,29.711023,2024366,2140,GOES-EAST,FDC,30,25.656,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16630508,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839
6226,-91.287971,29.711025,2024366,2146,GOES-EAST,FDC,30,24.624,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16630522,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839
6223,-91.717228,29.921240,2024366,2150,GOES-EAST,ANALYSIS,31,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16630525,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839
6224,-91.300201,29.721111,2024366,2150,GOES-EAST,ANALYSIS,31,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16630526,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839
6225,-91.295729,29.721111,2024366,2150,GOES-EAST,ANALYSIS,31,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16630527,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839

In [27]:
df_unique_fires = df_sorted.drop_duplicates(subset="__index_level_0__")
df_unique

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,...,__index_level_0__,Satellite_1,Start,End,Density,geometry_1,date_1,start_datetime,end_datetime,__index_level_0___1
0,-91.113426,35.996613,2023172,1500,GOES-EAST,FDC,57,33.974,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349472,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
1,-89.221596,36.805637,2023172,1500,GOES-EAST,FDC,91,294.384,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349473,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
2,-89.215981,36.779930,2023172,1500,GOES-EAST,FDC,57,205.634,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349474,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
3,-89.122818,37.136791,2023172,1500,GOES-EAST,FDC,57,207.088,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349475,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
4,-90.036652,36.726215,2023172,1500,GOES-EAST,FDC,57,36.036,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4349487,GOES-EAST,2023172 0900,2023172 1500,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 22, 8, 195, 32, ...",2023-06-21,2023-06-21 09:00:00,2023-06-21 15:00:00,11218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2222939,-120.112990,38.232674,2023172,2022,NOAA 20,VIIRS,22,12.282,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4371760,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 249, 155, 240, 194, 1...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11225
2222940,-120.114120,38.236938,2023172,2022,NOAA 20,VIIRS,22,12.282,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4371761,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 249, 155, 240, 194, 1...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11225
2222941,-120.119480,38.235725,2023172,2022,NOAA 20,VIIRS,22,42.973,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4371762,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 249, 155, 240, 194, 1...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11225
2222942,-116.298820,43.471004,2023172,1938,SUOMI NPP,VIIRS,52,52.589,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4366735,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 158, 176, 232, 194, 6...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11228
2222943,-120.344620,37.900054,2023172,1840,GOES-WEST,ANALYSIS,91,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-06-21,...,4359775,GOES-WEST,2023172 1820,2023173 0210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 41, 67, 241, 194, 12,...",2023-06-21,2023-06-21 18:20:00,2023-06-22 02:10:00,11226

In [28]:
df_unique_smoke = df_sorted.drop_duplicates(subset="__index_level_0___1")
df_unique_smoke

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date,...,__index_level_0__,Satellite_1,Start,End,Density,geometry_1,date_1,start_datetime,end_datetime,__index_level_0___1
1305111,-97.835846,26.483723,2023001,1916,GOES-EAST,FDC,41,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1172,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 58, 217, 201, 194, 23...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,11
1305096,-80.951591,26.666142,2023001,2030,GOES-EAST,FDC,94,123.358,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-01,...,1584,GOES-EAST,2023001 1900,2023001 2240,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 202, 7, 162, 194, 20,...",2023-01-01,2023-01-01 19:00:00,2023-01-01 22:40:00,10
1305086,-80.932001,26.646460,2023002,1520,GOES-EAST,ANALYSIS,31,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,...,2226,GOES-EAST,2023002 1520,2023002 1650,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 149, 97, 162, 194, 29...",2023-01-02,2023-01-02 15:20:00,2023-01-02 16:50:00,12
1305058,-80.620445,27.031481,2023002,1700,GOES-EAST,FDC,94,134.378,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,...,2294,GOES-EAST,2023002 1640,2023002 1810,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 40, 186, 161, 194, 22...",2023-01-02,2023-01-02 16:40:00,2023-01-02 18:10:00,13
1305055,-79.727869,33.560068,2023002,1851,GOES-EAST,ANALYSIS,27,-999.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2023-01-02,...,2899,GOES-EAST,2023002 1700,2023002 2130,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 201, 123, 159, 194, 2...",2023-01-02,2023-01-02 17:00:00,2023-01-02 21:30:00,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8801,-91.623024,30.831423,2024366,1811,SUOMI NPP,VIIRS,31,2.832,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16628672,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 153, 118, 183, 194, 1...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32840
8793,-91.618706,29.832289,2024366,1811,SUOMI NPP,VIIRS,30,6.365,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16628652,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 180, 133, 184, 194, 4...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32839
8775,-98.350822,34.725479,2024366,1834,NOAA 20,VIIRS,91,19.355,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16628884,GOES-EAST,2024366 1740,2024366 2210,Medium,"[2, 4, 0, 0, 0, 0, 0, 0, 151, 223, 196, 194, 1...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32846
8774,-98.350822,34.725479,2024366,1834,NOAA 20,VIIRS,91,19.355,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16628884,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 24, 22, 197, 194, 218...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32842
8768,-93.636353,29.990486,2024366,1834,NOAA 20,VIIRS,31,30.208,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",2024-12-31,...,16628826,GOES-EAST,2024366 1740,2024366 2210,Light,"[2, 4, 0, 0, 0, 0, 0, 0, 55, 87, 187, 194, 235...",2024-12-31,2024-12-31 17:40:00,2024-12-31 22:10:00,32841

In [21]:
df_sorted.to_parquet("fire_smoke_matches.parquet", index=False)

# filtering data with buffer

In [ ]:
buffer_10km_df = con.execute("""
    SELECT f.*, s.* 
    FROM 'fire_in_usa.parquet' f 
    JOIN 'smoke_in_usa.parquet' s 
    ON ST_Within(f.geometry, ST_Buffer(s.geometry, 10000))  -- buffer in meters (10 km) 
    WHERE f.datetime_full BETWEEN s.start_datetime AND s.end_datetime
""").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
buffer_10km_sorted = buffer_10km_df.sort_values(by='datetime_full', ascending=True)
buffer_10km_sorted

# DUCKDB setup

# Exploration

In [15]:
all_fire_gdf.shape

(16630935, 10)

In [17]:
all_smoke_gdf

,Satellite,Start,End,Density,geometry,date
0,GOES-WEST,2023001 1300,2023001 1520,Light,"POLYGON ((-78.01863 21.33982, -78.19258 21.220...",2023-01-01
1,GOES-WEST,2023001 1300,2023001 1520,Light,"POLYGON ((-78.00032 21.90134, -78.08577 21.928...",2023-01-01
2,GOES-WEST,2023001 1300,2023001 1520,Light,"POLYGON ((-75.93948 20.29585, -75.97524 20.230...",2023-01-01
3,GOES-WEST,2023001 1300,2023001 1520,Light,"POLYGON ((-78.23426 21.68163, -78.41069 21.567...",2023-01-01
4,GOES-WEST,2023001 1300,2023001 1520,Light,"POLYGON ((-83.43208 22.70604, -83.88657 22.638...",2023-01-01
...,...,...,...,...,...,...
32842,GOES-EAST,2024366 1740,2024366 2210,Light,"POLYGON ((-98.37118 34.80186, -98.43123 34.744...",2024-12-31
32843,GOES-EAST,2024366 1740,2024366 2210,Light,"POLYGON ((-97.22263 19.93059, -98.50385 20.378...",2024-12-31
32844,GOES-EAST,2024366 1740,2024366 2210,Light,"POLYGON ((-92.95516 16.51232, -93.02767 16.448...",2024-12-31
32845,GOES-EAST,2024366 1740,2024366 2210,Light,"POLYGON ((-93.02767 15.9664, -93.0959 15.91949...",2024-12-31
32846,GOES-EAST,2024366 1740,2024366 2210,Medium,"POLYGON ((-98.36845 34.72816, -98.41213 34.646...",2024-12-31

In [19]:
all_smoke_gdf['date'] = pd.to_datetime(all_smoke_gdf['date'])
smoke_on_jan1 = all_smoke_gdf[all_smoke_gdf['date'] == pd.Timestamp('2024-01-01')]
smoke_on_jan1["area"] = smoke_on_jan1.geometry.area
smoke_on_jan1

,Satellite,Start,End,Density,geometry,date,area
20303,GOES-EAST,2024001 1230,2024001 1630,Light,"POLYGON ((-80.5811 26.59485, -80.55298 26.5932...",2024-01-01,0.009181
20304,GOES-EAST,2024001 1230,2024001 1630,Light,"POLYGON ((-80.49204 26.54954, -80.47641 26.549...",2024-01-01,0.007570
20305,GOES-EAST,2024001 1230,2024001 1630,Light,"POLYGON ((-80.66079 26.53235, -80.63891 26.530...",2024-01-01,0.006273
20306,GOES-EAST,2024001 1230,2024001 1630,Light,"POLYGON ((-80.82329 26.53235, -80.79048 26.518...",2024-01-01,0.008936
20307,GOES-EAST,2024001 1230,2024001 1630,Light,"POLYGON ((-80.75766 26.58704, -80.74829 26.574...",2024-01-01,0.006360
20308,GOES-EAST,2024001 1230,2024001 1630,Light,"POLYGON ((-81.19491 26.86233, -81.18866 26.846...",2024-01-01,0.004039
20309,GOES-EAST,2024001 1230,2024001 1630,Light,"POLYGON ((-80.70523 26.69952, -80.74648 26.742...",2024-01-01,0.031352
20310,GOES-EAST,2024001 1230,2024001 1630,Light,"POLYGON ((-80.56648 26.87077, -80.53898 26.852...",2024-01-01,0.007752
20311,GOES-EAST,2024001 1230,2024001 1630,Light,"POLYGON ((-104.23504 19.74107, -104.27899 19.7...",2024-01-01,0.003728
20312,GOES-EAST,2024001 1740,2024001 2300,Light,"POLYGON ((-93.74772 31.89188, -93.90412 31.708...",2024-01-01,0.086024
20313,GOES-EAST,2024001 1740,2024001 2300,Light,"POLYGON ((-92.12647 30.96109, -92.2371 30.7932...",2024-01-01,0.084612
20314,GOES-EAST,2024001 1740,2024001 2300,Light,"POLYGON ((-84.28266 32.6286, -84.14914 32.5027...",2024-01-01,0.083535
20315,GOES-EAST,2024001 1740,2024001 2300,Light,"POLYGON ((-89.19529 31.89183, -89.20623 31.785...",2024-01-01,0.057555
20316,GOES-EAST,2024001 1740,2024001 2300,Light,"POLYGON ((-99.31841 31.90196, -99.34129 31.764...",2024-01-01,0.141532
20317,GOES-EAST,2024001 1740,2024001 2300,Light,"POLYGON ((-121.21796 38.1767, -121.22382 38.11...",2024-01-01,0.021566

In [21]:
all_fire_gdf['date'] = pd.to_datetime(all_fire_gdf['date'])
fire_on_jan1 = all_fire_gdf[all_fire_gdf['date'] == pd.Timestamp('2024-01-01')]
fire_on_jan1

,Lon,Lat,YearDay,Time,Satellite,Method,Ecosystem,FRP,geometry,date
8196303,-76.739235,37.548000,2024001,0641,NOAA 20,VIIRS,24,1.548,POINT (-76.73924 37.548),2024-01-01
8196304,-89.794058,35.818020,2024001,0646,NOAA 20,ANALYSIS,57,-999.000,POINT (-89.79406 35.81802),2024-01-01
8196305,-90.439829,30.955602,2024001,0646,NOAA 20,ANALYSIS,27,-999.000,POINT (-90.43983 30.9556),2024-01-01
8196306,-90.201829,30.573602,2024001,0646,NOAA 20,ANALYSIS,27,-999.000,POINT (-90.20183 30.5736),2024-01-01
8196307,-90.682829,30.674602,2024001,0646,NOAA 20,ANALYSIS,27,-999.000,POINT (-90.68283 30.6746),2024-01-01
...,...,...,...,...,...,...,...,...,...,...
8198502,-94.033150,16.242603,2024002,0540,GOES-EAST,FDC,91,37.981,POINT (-94.03315 16.2426),2024-01-01
8198503,-94.033150,16.242605,2024002,0541,GOES-EAST,FDC,91,33.102,POINT (-94.03315 16.2426),2024-01-01
8198504,-94.033150,16.242603,2024002,0550,GOES-EAST,FDC,91,26.215,POINT (-94.03315 16.2426),2024-01-01
8198505,-94.033150,16.242605,2024002,0551,GOES-EAST,FDC,91,21.342,POINT (-94.03315 16.2426),2024-01-01
8198506,-94.033150,16.242605,2024002,0556,GOES-EAST,FDC,91,28.434,POINT (-94.03315 16.2426),2024-01-01

In [57]:
smoke_on_jan1.explore()

In [133]:
smoke_on_jan1.shape

(15, 7)

# SANITY CHECK

In [47]:
# setting a random date

def randomDates():
    start_date = datetime(2023, 1, 1)
    end_date = datetime(2024, 12, 31)

    # Calculate the number of days between the two dates
    delta = end_date - start_date

    # Generate a random number of days to add
    random_days = random.randint(0, delta.days)

    # Create the random date
    random_date = start_date + timedelta(days=random_days)

    # Format the date as YYYY-MM-DD
    return random_date.strftime('%Y-%m-%d')


num = 3 
random_dates = sorted([randomDates() for _ in range(num)])

print(random_dates)

['2023-01-04', '2024-03-20', '2024-10-27']

In [49]:
n = 0

In [51]:
all_smoke_gdf['date'] = pd.to_datetime(all_smoke_gdf['date'])
smoke_on_date = all_smoke_gdf[all_smoke_gdf['date'] == pd.Timestamp(random_dates[n]) ]
smoke_on_date["area"] = smoke_on_date.geometry.area
smoke_on_date.shape

(132, 7)

In [53]:
# returns fires from random date [n]
fire_on_date = all_fire_gdf[all_fire_gdf['date'] == pd.Timestamp(random_dates[n]) ]
fire_on_date.shape

(8809, 10)

In [92]:
def show_fire_smoke_map(fire_on_date, smoke_on_date):

  m = folium.Map()
    # Fallback center if fire data is empty
  if not smoke_on_date.empty:
    smoke_copy = smoke_on_date.copy()

    # Convert datetimes to strings
    for col in smoke_copy.select_dtypes(include=['datetime64[ns]', 'datetime64']):
        smoke_copy[col] = smoke_copy[col].astype(str)

    # Define a default get_color function
    def get_color(density):
        return 'gray'  # fallback color if density info is missing

    if 'density' in smoke_copy.columns:
        # Normalize the density values
        max_density = smoke_copy['density'].max()
        min_density = smoke_copy['density'].min()
        range_density = max_density - min_density if max_density != min_density else 1

        def get_color(density):  # overwrite fallback
            norm = (density - min_density) / range_density
            if norm < 0.33:
                return 'yellow'    # Low density
            elif norm < 0.66:
                return 'orange'    # Medium density
            else:
                return 'red'       # High density

    def style_function(feature):
        density = feature['properties'].get('density', 0)
        return {
            'fillColor': get_color(density),
            'color': get_color(density),
            'weight': 1,
            'fillOpacity': 0.5
        }

    folium.GeoJson(
        smoke_copy.to_json(),
        name='Smoke Layer',
        style_function=style_function,
        tooltip=folium.GeoJsonTooltip(fields=['density'] if 'density' in smoke_copy.columns else [])
    ).add_to(m)

    return m

In [94]:
show_fire_smoke_map(fire_on_date, smoke_on_date)

In [132]:
def filter_fire_near_smoke(fire, smoke, buffer_km=10):
    smoke_buffered = smoke.copy()
    smoke_buffered['geometry'] = smoke_buffered.geometry.buffer(buffer_km * 1000)

    # Spatial join: find fires within (buffered) smoke polygons
    fire_near_smoke = gpd.sjoin(fire, smoke_buffered, how='inner', predicate='intersects')
    fire_near_smoke = fire_near_smoke.drop_duplicates(subset='geometry')

    return fire_near_smoke

In [142]:
def filter_smoke_with_fire(smoke, fire, buffer_km=10):

    smoke_buffered = smoke.copy()
    smoke_buffered["geometry"] = smoke_buffered.geometry.buffer(buffer_km * 1000)

    # Spatial join: which fire points intersect the buffered smoke polygons
    joined = gpd.sjoin(smoke_buffered, fire, how='inner', predicate='intersects')

    # Keep only original smoke polygons whose buffered versions had fire points
    smoke_with_fire = smoke.loc[smoke.index.isin(joined.index)]
    smoke_with_fire = smoke_with_fire.drop_duplicates(subset='geometry')

    return smoke_with_fire

In [144]:
filter_smoke = filter_smoke_with_fire(smoke_on_date, fire_on_date)
filter_smoke.shape

(35, 7)

In [164]:
filter_fire = filter_fire_near_smoke(fire_on_date,smoke_on_date)
filter_fire.shape

(2072, 17)

In [171]:
fire = all_fire_gdf.to_crs(usa_full.crs)
smoke = all_smoke_gdf.to_crs(usa_full.crs)